# Generated by Django 4.1.4 on 2023-03-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazinlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazin', models.CharField(max_length=500)),
                ('tarif', models.TextField(blank=True, help_text='locatsiya , ism va boshqa izohlar', null=True)),
            ],
            options={
                'verbose_name': 'Magazin',
                'verbose_name_plural': 'Magazinlar',
            },
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=500)),
                ('narx', models.IntegerField(help_text="so'm")),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sana', models.DateField()),
                ('sababi', models.CharField(max_length=500)),
                ('narxi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
            },
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.IntegerField(default=0, help_text='dona')),
                ('chegirma_narxi', models.IntegerField(default=0, help_text="agar chegirma narx bo'lsa")),
                ('sana', models.DateField(blank=True, null=True)),
                ('qarz_tulandi', models.BooleanField()),
                ('olingan_pul', models.IntegerField(default=0, help_text="so'm")),
                ('dukon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.magazinlar')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mahsulotlar')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdo',
            },
        ),
    ]
